trigger:
  branches:
    include:
    - main
    - develop
  paths:
    include:
    - patient-service/**
    - application-service/**
    - order-service/**
    - k8s/**
    - azure-pipelines.yml

variables:

  ACR_NAME: 'acrashhackathon' 
  ACR_SERVICE_CONNECTION: 'your-acr-service-connection'
  
  # AKS variables
  AKS_CLUSTER_NAME: 'hackathon-akash'
  AKS_RESOURCE_GROUP: 'hackathon-0811-AkashSoam' 
  AKS_SERVICE_CONNECTION: 'your-aks-service-connection' 
  
  # Image tags
  IMAGE_TAG: 'latest'
  
  # Service names
  PATIENT_SERVICE_IMAGE: '$(ACR_NAME).azurecr.io/patient-service:$(IMAGE_TAG)'
  APPLICATION_SERVICE_IMAGE: '$(ACR_NAME).azurecr.io/application-service:$(IMAGE_TAG)'
  ORDER_SERVICE_IMAGE: '$(ACR_NAME).azurecr.io/order-service:$(IMAGE_TAG)'

stages:
- stage: Build
  displayName: 'Build and Push Docker Images'
  jobs:
  - job: BuildPatientService
    displayName: 'Build Patient Service'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build Patient Service Image'
      inputs:
        command: 'build'
        repository: 'patient-service'
        dockerfile: '$(Build.SourcesDirectory)/patient-service/Dockerfile'
        containerRegistry: '$(ACR_SERVICE_CONNECTION)'
        tags: |
          $(IMAGE_TAG)
          latest
    
    - task: Docker@2
      displayName: 'Push Patient Service Image'
      inputs:
        command: 'push'
        repository: 'patient-service'
        containerRegistry: '$(ACR_SERVICE_CONNECTION)'
        tags: |
          $(IMAGE_TAG)
          latest

  - job: BuildApplicationService
    displayName: 'Build Application Service'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build Application Service Image'
      inputs:
        command: 'build'
        repository: 'application-service'
        dockerfile: '$(Build.SourcesDirectory)/application-service/Dockerfile'
        containerRegistry: '$(ACR_SERVICE_CONNECTION)'
        tags: |
          $(IMAGE_TAG)
          latest
    
    - task: Docker@2
      displayName: 'Push Application Service Image'
      inputs:
        command: 'push'
        repository: 'application-service'
        containerRegistry: '$(ACR_SERVICE_CONNECTION)'
        tags: |
          $(IMAGE_TAG)
          latest

  - job: BuildOrderService
    displayName: 'Build Order Service'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      displayName: 'Maven Build Order Service'
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/order-service/pom.xml'
        goals: 'clean package'
        options: '-DskipTests'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
    
    - task: Docker@2
      displayName: 'Build Order Service Image'
      inputs:
        command: 'build'
        repository: 'order-service'
        dockerfile: '$(Build.SourcesDirectory)/order-service/Dockerfile'
        containerRegistry: '$(ACR_SERVICE_CONNECTION)'
        tags: |
          $(IMAGE_TAG)
          latest
    
    - task: Docker@2
      displayName: 'Push Order Service Image'
      inputs:
        command: 'push'
        repository: 'order-service'
        containerRegistry: '$(ACR_SERVICE_CONNECTION)'
        tags: |
          $(IMAGE_TAG)
          latest

- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployToAKS
    displayName: 'Deploy all services to AKS'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          
          - task: KubernetesManifest@0
            displayName: 'Create imagePullSecret'
            inputs:
              action: 'createSecret'
              kubernetesServiceConnection: '$(AKS_SERVICE_CONNECTION)'
              secretType: 'dockerRegistry'
              secretName: 'acr-secret'
              dockerRegistryEndpoint: '$(ACR_SERVICE_CONNECTION)'
          
          # Deploy Patient Service
          - task: replacetokens@5
            displayName: 'Replace tokens in Patient Service manifests'
            inputs:
              rootDirectory: '$(Build.SourcesDirectory)/k8s/patient-service'
              targetFiles: '**/*.yaml'
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              actionOnNoFiles: 'continue'
              enableTransforms: false
              enableRecursion: false
              useLegacyPattern: false
              enableTelemetry: true
          
          - task: KubernetesManifest@0
            displayName: 'Deploy Patient Service'
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: '$(AKS_SERVICE_CONNECTION)'
              namespace: 'default'
              manifests: |
                $(Build.SourcesDirectory)/k8s/patient-service/deployment.yaml
                $(Build.SourcesDirectory)/k8s/patient-service/service.yaml
              imagePullSecrets: 'acr-secret'
          
          # Deploy Application Service
          - task: replacetokens@5
            displayName: 'Replace tokens in Application Service manifests'
            inputs:
              rootDirectory: '$(Build.SourcesDirectory)/k8s/application-service'
              targetFiles: '**/*.yaml'
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              actionOnNoFiles: 'continue'
              enableTransforms: false
              enableRecursion: false
              useLegacyPattern: false
              enableTelemetry: true
          
          - task: KubernetesManifest@0
            displayName: 'Deploy Application Service'
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: '$(AKS_SERVICE_CONNECTION)'
              namespace: 'default'
              manifests: |
                $(Build.SourcesDirectory)/k8s/application-service/deployment.yaml
                $(Build.SourcesDirectory)/k8s/application-service/service.yaml
              imagePullSecrets: 'acr-secret'
          
          # Deploy Order Service
          - task: replacetokens@5
            displayName: 'Replace tokens in Order Service manifests'
            inputs:
              rootDirectory: '$(Build.SourcesDirectory)/k8s/order-service'
              targetFiles: '**/*.yaml'
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              actionOnNoFiles: 'continue'
              enableTransforms: false
              enableRecursion: false
              useLegacyPattern: false
              enableTelemetry: true
          
          - task: KubernetesManifest@0
            displayName: 'Deploy Order Service'
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: '$(AKS_SERVICE_CONNECTION)'
              namespace: 'default'
              manifests: |
                $(Build.SourcesDirectory)/k8s/order-service/deployment.yaml
                $(Build.SourcesDirectory)/k8s/order-service/service.yaml
              imagePullSecrets: 'acr-secret'
          
          - task: Kubernetes@1
            displayName: 'Get deployed services'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: '$(AKS_SERVICE_CONNECTION)'
              command: 'get'
              arguments: 'services'
